INSERT INTO MS_ENTIDAD_ADMINISTRADORA (ID, ER_NIT, ER_NOMBRE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY,LAST_MODIFIED_DATE)VALUES ('1OLGFSADV1237FA0D321F123431CF08A', '8301011605', 'BIOTRENDS LABORATORIOS','System',sysdate,' ',sysdate);
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY STRING_VAL VARCHAR2(500);
